### ISSUE TITLE
[feature] Show dialog prompting user to pick up the phone

### ISSUE THREAD

**Issue by Johann-Tree** [mmitch/fritzdial#1]
Could you implement a dialog similar to http://www.schniewind-it.de/dlfiles/public/LINUX/fritzdial.sh ?

I switched to your script since that one wasn't working anymore with the current version of FRITZ!OS: 06.50

**Comment by mmitch** [comment]
The basic answer would be "no", because I don't want to mix the fritzdial script with some kind of GUI.  If anybody would want that, he should directly write a GUI program using `Net::Fritz::Box`.

But luckily we're in Unix land here so we can just plug some things together and display the dialog outside of `fritzdial`:

As far as I understand the above script, it just dials and then displays a dialog via zenity.
`fritzdial` allows non-interactive batch operation via the `-` parameter, so you could use a simple script like this to dial and display a dialog that the dialing is in progress.  The number to dial (or a shortcut from your `~/.fritzdialrc`) must be passed as the first commandline argument to the script:

``` bash
#!/bin/sh
DIALNUMBER="$1"
COMMAND="dial ${DIALNUMBER}"
if echo $COMMAND | fritzdial - ; then
    zenity --auto-close --title "FB-Anruf bei ${DIALNUMBER}" --pulsate --progress --text="Anwahl ${DIALNUMBER}..."
else
    # error handling goes here
fi
```

The script is untested, but you should get the idea.
I have removed the Nebenstelle from the dialog because you can only set one dial help via the web interface anyways, so you can just hardcode it in the message text if you need that.

Hope this helps!  (if not, please leave an additional comment)
